name: Deploy Website
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Frontend
        run: |
          cd apps/frontend
          yarn install
          yarn build

      - name: Deploy to S3
        run: |
          aws s3 sync apps/frontend/dist s3://${{ secrets.S3_BUCKET }} --delete
