name: Deploy Website
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  AWS_ACCESS_KEY_ID_DEV: ${{ secrets.AWS_ACCESS_KEY_ID_DEV}}
  AWS_SECRET_ACCESS_KEY_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET_DEV: ${{ secrets.S3_BUCKET_DEV }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Frontend
        run: |
          cd apps/frontend
          yarn install
          yarn build

      - name: Deploy to S3
        run: |
          aws s3 sync apps/frontend/dist s3://${{ env.S3_BUCKET_DEV }} --delete
